# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |cards = [Ah,As,Ac,Ad,Kh,Ks,Kc,Kd,Qh,Qs,Qc,Qd,Jh,Js,Jc,Jd,10h,10s,10c,10d,9h,9s,9c,9d,8h,8s,8c,8d,7h,7s,7c,7d,6h,6s,6c,6d,5h,5s,5c,5d,4h,4s,4c,4d,3h,3s,3c,3d,2h,2s,2c,2d] 
            |print(cards)
          echo Add other actions to build,
          echo test, and deploy your project.
